version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-portfolio-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
